# Generated by Django 2.1.7 on 2019-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190910_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/media/noprofile.png', null=True, upload_to='images/'),
        ),
    ]
