# Generated by Django 2.1.7 on 2019-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190910_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
