# Generated by Django 2.1.7 on 2019-09-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postlike_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='count',
        ),
    ]
