# Generated by Django 2.1.7 on 2019-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_postlike_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
