# Generated by Django 2.1.7 on 2019-09-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_postlike_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='count',
        ),
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
