# Generated by Django 2.1.7 on 2019-09-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
