# Generated by Django 2.1.7 on 2019-09-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190910_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='flag',
        ),
    ]
